### ISSUE TITLE
VIDIOC_S_CTRL: Input/output error

### ISSUE THREAD

**Issue by BhavaniIT** [diegoinacio/object-detection-flask-opencv#2]
![Screenshot from 2020-03-07 11-41-01](https://user-images.githubusercontent.com/53058170/76137960-91f77380-6068-11ea-9850-60e911ad69c0.png)

It gives me Input/Output error.So, that the camera is not opening. Could you please help me to rectify this error?

**Comment by Mohamed-Khalil67** [comment]
![187150164_311949687220866_35283662905733763_n](https://user-images.githubusercontent.com/71330579/118408344-7da80100-b685-11eb-91bc-6df5868bd600.jpg)

**Comment by Mohamed-Khalil67** [comment]
Hi , i think there is something in code where the camera cannot by opened by index can u help me please?
![Uploading 187150164_311949687220866_35283662905733763_n.jpg…]()
