### ISSUE TITLE
can't open camera by index

### ISSUE THREAD

**Issue by Mohamed-Khalil67** [diegoinacio/object-detection-flask-opencv#5]
![187150164_311949687220866_35283662905733763_n](https://user-images.githubusercontent.com/71330579/118409592-65d37b80-b68b-11eb-9033-303e5b4498f4.jpg)

Can u help me please solve this bug , i have no camera view on my raspberry pi 4

**Comment by hiankun** [comment]
For people who have encountered the same issue, try to add `use_reloader=False` in the following line of `application.py`:
```
application.run(debug=True, use_reloader=False)
```

Source: https://stackoverflow.com/a/61918743
