### ISSUE TITLE
Why need to put contrast and exposure?

### ISSUE THREAD

**Issue by fitrihakim** [diegoinacio/object-detection-flask-opencv#6]
Hi I already have yolov3 detection model. However, when I implement them using ur code, the detection becomes quite hard. The fps become more lagging. I think maybe it relay to the contrast and exposure.

**Comment by diegoinacio** [comment]
Hi @fitrihakim 
Actually this repo is a clean version of a real project I did.
It was supposed to run in a embeded system and has bunches of requirements, including all of those controls and some image processing steps. I could optimize it before sharing here, but the main purpose of this repo was to help people to find a way to deploy an object detection application using Flask and OpenCV. 
But you are completely right about the performance.. I would have done differently if this project was mine and it didn't have the image processing steps.

**Comment by fitrihakim** [comment]
Hi @diegoinacio , thank you for your time in replying to my question. May I ask ur opinion, is it okay if I just remove all contrast and brightness features? Because actually I did remove the features but the webcam didn't on at the web page. I want to deploy my object detection model (yolov3) without need to setup any webcam settings. Thank you.

**Comment by diegoinacio** [comment]
Hi @fitrihakim 
Yes, absolutely.. as I said, the controls (exposure, contrast ..) were requirements when I got the project.
You definitely can remove all those features, the detection step does not depend on them.
